services:
  mysql:
    image: mysql:8.0
    container_name: crm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_single
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
